/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as BookSlugSuccessRouteImport } from './routes/book.$slug.success'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated.dashboard.settings'
import { Route as AuthenticatedDashboardServicesRouteImport } from './routes/_authenticated.dashboard.services'
import { Route as AuthenticatedDashboardDiscountsRouteImport } from './routes/_authenticated.dashboard.discounts'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated.dashboard.bookings'
import { Route as AuthenticatedDashboardAvailabilityRouteImport } from './routes/_authenticated.dashboard.availability'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated.dashboard.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const BookSlugSuccessRoute = BookSlugSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookSlugRoute,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardServicesRoute =
  AuthenticatedDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDiscountsRoute =
  AuthenticatedDashboardDiscountsRouteImport.update({
    id: '/discounts',
    path: '/discounts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAvailabilityRoute =
  AuthenticatedDashboardAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/book/$slug': typeof BookSlugRouteWithChildren
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/book/$slug/success': typeof BookSlugSuccessRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/book/$slug': typeof BookSlugRouteWithChildren
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/book/$slug/success': typeof BookSlugSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/book/$slug': typeof BookSlugRouteWithChildren
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/discounts': typeof AuthenticatedDashboardDiscountsRoute
  '/_authenticated/dashboard/services': typeof AuthenticatedDashboardServicesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/book/$slug/success': typeof BookSlugSuccessRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/book/$slug'
    | '/dashboard/analytics'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/discounts'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/book/$slug/success'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/book/$slug'
    | '/dashboard/analytics'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/discounts'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/book/$slug/success'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/book/$slug'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/availability'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/discounts'
    | '/_authenticated/dashboard/services'
    | '/_authenticated/dashboard/settings'
    | '/book/$slug/success'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BookSlugRoute: typeof BookSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/book/$slug/success': {
      id: '/book/$slug/success'
      path: '/success'
      fullPath: '/book/$slug/success'
      preLoaderRoute: typeof BookSlugSuccessRouteImport
      parentRoute: typeof BookSlugRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/services': {
      id: '/_authenticated/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof AuthenticatedDashboardServicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/discounts': {
      id: '/_authenticated/dashboard/discounts'
      path: '/discounts'
      fullPath: '/dashboard/discounts'
      preLoaderRoute: typeof AuthenticatedDashboardDiscountsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/availability': {
      id: '/_authenticated/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof AuthenticatedDashboardAvailabilityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardAvailabilityRoute: typeof AuthenticatedDashboardAvailabilityRoute
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardDiscountsRoute: typeof AuthenticatedDashboardDiscountsRoute
  AuthenticatedDashboardServicesRoute: typeof AuthenticatedDashboardServicesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardAvailabilityRoute:
      AuthenticatedDashboardAvailabilityRoute,
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardDiscountsRoute: AuthenticatedDashboardDiscountsRoute,
    AuthenticatedDashboardServicesRoute: AuthenticatedDashboardServicesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BookSlugRouteChildren {
  BookSlugSuccessRoute: typeof BookSlugSuccessRoute
}

const BookSlugRouteChildren: BookSlugRouteChildren = {
  BookSlugSuccessRoute: BookSlugSuccessRoute,
}

const BookSlugRouteWithChildren = BookSlugRoute._addFileChildren(
  BookSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BookSlugRoute: BookSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
